### ISSUE TITLE
    x86_64-linux-gnu-gcc: error: csgraph_mod/shortest_path_mod.c: No such file or directory

### ISSUE THREAD

**Issue by gonzaparra** [soedinglab/csgraph_mod#1]
The following file is missing /csgraph_mod/shortest_path_mod.c

I added it to the folder and I was able to install the package correctly.

**Comment by galicae** [comment]
can you give me more info? When I tried a fresh install this did not happen. I fixed a couple of other things that prevented an installation, but never had this particular error message. The .c file is generated from the .pyx during setup, hence why we don't ship it.

**Comment by gonzaparra** [comment]
![image](https://user-images.githubusercontent.com/6352196/29411027-7eef8fb0-8353-11e7-97f3-9e6e61a85efc.png)

**Comment by galicae** [comment]
turns out that in order to compile cython code you need to have installed cython :thinking: who would have thought... Updated the README in order to reflect this, might look into how to install dependencies automatically in a later release.

**Comment by croth1** [comment]
Niko, the idea is to submit the auto generated *.c files to the repository. The setup.py uses cython if it is present - if not it tries to fall back to the *.c files.

**Comment by galicae** [comment]
isn't the idea though that the c files are going to reflect the architecture of the OS? Also, cython isn't a monstrous dependency to have. This has been [discussed](https://github.com/enthought/traits/issues/314) [elsewhere](https://github.com/MDAnalysis/mdanalysis/issues/667). There is no recommended best practice, the best I could find was (as always) this [SO comment](https://stackoverflow.com/questions/4505747/how-should-i-structure-a-python-package-that-contains-cython-code) (where you probably stole the cython setup.py from anyway). I would be grateful for suggestions!

**Comment by croth1** [comment]
well the setup.py I ~~stole~~ borrowed uses cython as an optional dependency and expects the c files in the repository. It's easy to adapt the setup.py to make cython a mandatory dependency. I have no strong opinions what the best way is.
